version: '3.8'

services:
  znn-wallet-api:
    image: znn-wallet-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: znn-wallet-api
    restart: unless-stopped
    ports:
      - "${API_HTTP_PORT:-8080}:80"
      - "${API_HTTPS_PORT:-8443}:443"
    environment:
      # ASP.NET Core settings
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://+:80;https://+:443}
      
      # JWT Configuration
      - Api__Jwt__Secret=${API_JWT_SECRET}
      - Api__Jwt__ValidIssuer=${API_JWT_VALID_ISSUER:-walletapi.zenon.network}
      - Api__Jwt__ValidAudience=${API_JWT_VALID_AUDIENCE:-zenon.network}
      - Api__Jwt__ExpiresAfter=${API_JWT_EXPIRES_AFTER:-}
      
      # Node Configuration
      - Api__Node__NodeUrl=${API_NODE_URL:-ws://host.docker.internal:35998}
      - Api__Node__ChainId=${API_NODE_CHAIN_ID:-1}
      - Api__Node__ProtocolVersion=${API_NODE_PROTOCOL_VERSION:-1}
      - Api__Node__MaxPoWThreads=${API_NODE_MAX_POW_THREADS:-5}
      - Api__Node__PlasmaMode=${API_NODE_PLASMA_MODE:-PoW}
      - Api__Node__MinQsrThreshold=${API_NODE_MIN_QSR_THRESHOLD:-100}
      - Api__Node__FuseTimeout=${API_NODE_FUSE_TIMEOUT:-00:01:00}
      
      # Wallet Configuration
      - Api__Wallet__Path=/app/wallet
      - Api__Wallet__Name=${API_WALLET_NAME:-api}
      - Api__Wallet__EraseLimit=${API_WALLET_ERASE_LIMIT:-3}
      
      # AutoReceiver Configuration
      - Api__AutoReceiver__Enabled=${API_AUTORECEIVER_ENABLED:-true}
      - Api__AutoReceiver__TimerInterval=${API_AUTORECEIVER_TIMER_INTERVAL:-00:00:05}
      
      # AutoLocker Configuration
      - Api__AutoLocker__Enabled=${API_AUTOLOCKER_ENABLED:-true}
      - Api__AutoLocker__LockTimeout=${API_AUTOLOCKER_LOCK_TIMEOUT:-00:05:00}
      - Api__AutoLocker__TimerInterval=${API_AUTOLOCKER_TIMER_INTERVAL:-00:00:05}
      
      # PlasmaBot Configuration
      - Api__Utilities__PlasmaBot__ApiKey=${API_PLASMABOT_APIKEY}
      - Api__Utilities__PlasmaBot__ApiUrl=${API_PLASMABOT_APIURL:-https://zenonhub.io/api/utilities/plasma-bot/}
      
      # Logging
      - Serilog__MinimumLevel=${SERILOG_MINIMUM_LEVEL:-Information}
    volumes:
      - wallet_data:/app/wallet
      - ./appsettings.Docker.json:/app/appsettings.Docker.json:ro
      - ./certs:/https:ro  # Optional: for HTTPS certificates
    networks:
      - zenon-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/wallet/status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  wallet_data:
    driver: local

networks:
  zenon-network:
    driver: bridge
    name: zenon-network