name: CI

on:
  push:
    branches-ignore:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  WORK_DIR: './src'
  
jobs:
  ci:
    name: ci-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install Nerdbank Git versioning
      run: dotnet tool install -g nbgv
    - name: Setup Nerdbank Git versioning
      run: nbgv install
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORK_DIR }}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.WORK_DIR }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{ env.WORK_DIR }}